### PR TITLE
Added feels like temperature

### PR DESCRIPTION
**Pull request by gittyupcowboy**

### CODE REVIEW

**Comment by gittyupcowboy** [comment]
@marcokreeft87 - I can't seem to get this configured correctly - it just kind of ... floats, any thoughts?
image

**Comment by marcokreeft87** [comment]
Check bottom part of my PR https://github.com/bramkragten/weather-card/pull/143/commits/f6734d5cd0748e039b76c1c6fc15f1320a1a5440

**Comment by gittyupcowboy** [comment]
Not sure how I missed that; thanks. I'm tinkering with adding a UI feature for it. My JS, et. al is weak sauce. Figured this was a low stake enough project to mess around on. 

Thanks Marco.

**Comment by marcokreeft87** [comment]
No worries, you gotta start somewhere

**Pull request merged**
